import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

export default function Home({ locale }) {
  const router = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About GAMA Healthcare</h1>
        <p className={styles.description}>
          Your current locale is {router.locale}
        </p>

        {router.locale === 'en-GB' && (
          <p className={styles.description}>
            GAMA Healthcare is a dynamic, innovative company at the forefront of
            infection prevention technology. We specialise in the manufacture
            and distribution of revolutionary IPC products and the provision of
            exceptional aftercare support.
          </p>
        )}

        {router.locale === 'fr' && (
          <p className={styles.description}>
            GAMA Healthcare est une entreprise dynamique et innovante à la
            pointe de la technologie de prévention des infections. Nous sommes
            spécialisés dans la fabrication et la distribution de produits IPC
            révolutionnaires et dans la fourniture d&lsquo;un service
            après-vente exceptionnel.
          </p>
        )}

        <Link href='/' passHref>
          <a className={styles.button}>Home</a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
